import type { PlantDefinition } from '@/domain/plants/models';

const timestamp = '2026-01-15T00:00:00.000Z';

export const seedPlantLibrary: PlantDefinition[] = [
  {
    id: 'seed-tomato',
    commonName: 'Tomato',
    varietyName: 'Sun Gold',
    plantFamily: 'Solanaceae',
    category: 'fruiting',
    lifecycle: 'annual',
    spacingMm: 610,
    spreadMm: 610,
    heightMm: 1524,
    sunRequirement: 'fullSun',
    waterRequirement: 'moderate',
    daysToMaturity: 65,
    plantingWindowStartMonth: 4,
    plantingWindowEndMonth: 6,
    successionIntervalDays: null,
    companionPlantNames: ['Basil', 'Marigold'],
    conflictPlantNames: [],
    preferredZoneTypes: ['raisedBed', 'inGroundBed', 'trellis'],
    notes: 'Sweet cherry tomato for trellised beds.',
    isFavorite: true,
    isCustom: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 'seed-basil',
    commonName: 'Basil',
    varietyName: 'Genovese',
    plantFamily: 'Lamiaceae',
    category: 'herb',
    lifecycle: 'annual',
    spacingMm: 203,
    spreadMm: 203,
    heightMm: 457,
    sunRequirement: 'fullSun',
    waterRequirement: 'moderate',
    daysToMaturity: 50,
    plantingWindowStartMonth: 5,
    plantingWindowEndMonth: 8,
    successionIntervalDays: 21,
    companionPlantNames: ['Tomato'],
    conflictPlantNames: [],
    preferredZoneTypes: ['raisedBed', 'inGroundBed', 'container'],
    notes: 'Fast, fragrant basil for containers and bed edges.',
    isFavorite: false,
    isCustom: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 'seed-carrot',
    commonName: 'Carrot',
    varietyName: 'Nantes',
    plantFamily: 'Apiaceae',
    category: 'root',
    lifecycle: 'annual',
    spacingMm: 76,
    spreadMm: 76,
    heightMm: 305,
    sunRequirement: 'fullSun',
    waterRequirement: 'moderate',
    daysToMaturity: 70,
    plantingWindowStartMonth: 3,
    plantingWindowEndMonth: 8,
    successionIntervalDays: 14,
    companionPlantNames: ['Thyme'],
    conflictPlantNames: [],
    preferredZoneTypes: ['raisedBed', 'inGroundBed'],
    notes: 'Reliable root crop for dense sowing rows.',
    isFavorite: false,
    isCustom: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 'seed-kale',
    commonName: 'Kale',
    varietyName: 'Lacinato',
    plantFamily: 'Brassicaceae',
    category: 'leafy',
    lifecycle: 'annual',
    spacingMm: 457,
    spreadMm: 457,
    heightMm: 762,
    sunRequirement: 'fullSun',
    waterRequirement: 'moderate',
    daysToMaturity: 55,
    plantingWindowStartMonth: 3,
    plantingWindowEndMonth: 9,
    successionIntervalDays: 21,
    companionPlantNames: ['Thyme'],
    conflictPlantNames: ['Strawberry'],
    preferredZoneTypes: ['raisedBed', 'inGroundBed', 'container'],
    notes: 'Cold-tolerant leafy green for shoulder seasons.',
    isFavorite: false,
    isCustom: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 'seed-marigold',
    commonName: 'Marigold',
    varietyName: 'Gem',
    plantFamily: 'Asteraceae',
    category: 'flower',
    lifecycle: 'annual',
    spacingMm: 203,
    spreadMm: 203,
    heightMm: 305,
    sunRequirement: 'fullSun',
    waterRequirement: 'low',
    daysToMaturity: 55,
    plantingWindowStartMonth: 4,
    plantingWindowEndMonth: 6,
    successionIntervalDays: null,
    companionPlantNames: ['Tomato'],
    conflictPlantNames: [],
    preferredZoneTypes: ['raisedBed', 'inGroundBed', 'container'],
    notes: 'Compact border flower for pollinator support.',
    isFavorite: true,
    isCustom: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 'seed-strawberry',
    commonName: 'Strawberry',
    varietyName: 'Albion',
    plantFamily: 'Rosaceae',
    category: 'perennial',
    lifecycle: 'perennial',
    spacingMm: 305,
    spreadMm: 305,
    heightMm: 254,
    sunRequirement: 'fullSun',
    waterRequirement: 'moderate',
    daysToMaturity: 90,
    plantingWindowStartMonth: 3,
    plantingWindowEndMonth: 5,
    successionIntervalDays: null,
    companionPlantNames: [],
    conflictPlantNames: ['Kale'],
    preferredZoneTypes: ['container', 'orchardPerennial'],
    notes: 'Good for containers and dedicated perennial pockets.',
    isFavorite: false,
    isCustom: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 'seed-thyme',
    commonName: 'Thyme',
    varietyName: 'English',
    plantFamily: 'Lamiaceae',
    category: 'herb',
    lifecycle: 'perennial',
    spacingMm: 254,
    spreadMm: 254,
    heightMm: 203,
    sunRequirement: 'fullSun',
    waterRequirement: 'low',
    daysToMaturity: 85,
    plantingWindowStartMonth: 4,
    plantingWindowEndMonth: 6,
    successionIntervalDays: null,
    companionPlantNames: ['Carrot', 'Kale'],
    conflictPlantNames: [],
    preferredZoneTypes: ['container', 'herbSpiral', 'orchardPerennial'],
    notes: 'Dry-loving herb suited for spirals and containers.',
    isFavorite: false,
    isCustom: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];
