import { describe, expect, it } from 'vitest';

import type { PlannerDocument } from '@/domain/garden/models';
import { buildIrrigationRecommendations } from '@/domain/garden/irrigation';
import type { PlantDefinition } from '@/domain/plants/models';

const plannerDocument: PlannerDocument = {
  plan: {
    id: 'plan-1',
    name: 'Backyard Garden',
    locationLabel: 'Home',
    notes: '',
    measurementSystem: 'imperial',
    widthCells: 14,
    heightCells: 10,
    cellSizeMm: 305,
    seasonTag: '2026',
    seasonFamilyId: 'plan-1',
    sourcePlanId: null,
    createdAt: '2026-04-12T00:00:00.000Z',
    updatedAt: '2026-04-12T00:00:00.000Z',
  },
  zones: [
    {
      id: 'zone-1',
      gardenPlanId: 'plan-1',
      type: 'raisedBed',
      shape: 'rectangle',
      name: 'North Bed',
      notes: '',
      gridX: 1,
      gridY: 1,
      widthCells: 4,
      heightCells: 2,
      rotationDegrees: 0,
      styleKey: 'raised-bed',
      createdAt: '2026-04-12T00:00:00.000Z',
      updatedAt: '2026-04-12T00:00:00.000Z',
    },
    {
      id: 'zone-2',
      gardenPlanId: 'plan-1',
      type: 'container',
      shape: 'circle',
      name: 'Patio Pot',
      notes: '',
      gridX: 8,
      gridY: 1,
      widthCells: 2,
      heightCells: 2,
      rotationDegrees: 0,
      styleKey: 'container',
      createdAt: '2026-04-12T00:00:00.000Z',
      updatedAt: '2026-04-12T00:00:00.000Z',
    },
    {
      id: 'zone-3',
      gardenPlanId: 'plan-1',
      type: 'pathway',
      shape: 'rectangle',
      name: 'Main Path',
      notes: '',
      gridX: 0,
      gridY: 6,
      widthCells: 10,
      heightCells: 1,
      rotationDegrees: 0,
      styleKey: 'pathway',
      createdAt: '2026-04-12T00:00:00.000Z',
      updatedAt: '2026-04-12T00:00:00.000Z',
    },
  ],
  placements: [
    {
      id: 'placement-1',
      gardenPlanId: 'plan-1',
      plantDefinitionId: 'plant-1',
      zoneId: 'zone-1',
      notes: '',
      gridX: 2,
      gridY: 2,
      footprintWidthCells: 1,
      footprintHeightCells: 1,
      quantity: 1,
      layoutPattern: 'single',
      rotationDegrees: 0,
      createdAt: '2026-04-12T00:00:00.000Z',
      updatedAt: '2026-04-12T00:00:00.000Z',
    },
    {
      id: 'placement-2',
      gardenPlanId: 'plan-1',
      plantDefinitionId: 'plant-2',
      zoneId: 'zone-2',
      notes: '',
      gridX: 8,
      gridY: 1,
      footprintWidthCells: 1,
      footprintHeightCells: 1,
      quantity: 1,
      layoutPattern: 'single',
      rotationDegrees: 0,
      createdAt: '2026-04-12T00:00:00.000Z',
      updatedAt: '2026-04-12T00:00:00.000Z',
    },
    {
      id: 'placement-3',
      gardenPlanId: 'plan-1',
      plantDefinitionId: 'plant-3',
      zoneId: 'zone-1',
      notes: '',
      gridX: 4,
      gridY: 2,
      footprintWidthCells: 1,
      footprintHeightCells: 1,
      quantity: 1,
      layoutPattern: 'single',
      rotationDegrees: 0,
      createdAt: '2026-04-12T00:00:00.000Z',
      updatedAt: '2026-04-12T00:00:00.000Z',
    },
  ],
};

const plantDefinitions: PlantDefinition[] = [
  {
    id: 'plant-1',
    commonName: 'Tomato',
    varietyName: 'Roma',
    plantFamily: 'Solanaceae',
    category: 'fruiting',
    lifecycle: 'annual',
    spacingMm: 305,
    spreadMm: 305,
    heightMm: 900,
    sunRequirement: 'fullSun',
    waterRequirement: 'moderate',
    daysToMaturity: 75,
    plantingWindowStartMonth: 4,
    plantingWindowEndMonth: 6,
    successionIntervalDays: null,
    notes: '',
    isFavorite: false,
    isCustom: false,
    createdAt: '2026-04-12T00:00:00.000Z',
    updatedAt: '2026-04-12T00:00:00.000Z',
  },
  {
    id: 'plant-2',
    commonName: 'Mint',
    varietyName: 'Spearmint',
    plantFamily: 'Lamiaceae',
    category: 'herb',
    lifecycle: 'perennial',
    spacingMm: 305,
    spreadMm: 305,
    heightMm: 457,
    sunRequirement: 'partSun',
    waterRequirement: 'high',
    daysToMaturity: 60,
    plantingWindowStartMonth: 4,
    plantingWindowEndMonth: 8,
    successionIntervalDays: null,
    notes: '',
    isFavorite: false,
    isCustom: false,
    createdAt: '2026-04-12T00:00:00.000Z',
    updatedAt: '2026-04-12T00:00:00.000Z',
  },
  {
    id: 'plant-3',
    commonName: 'Lavender',
    varietyName: 'Munstead',
    plantFamily: 'Lamiaceae',
    category: 'flower',
    lifecycle: 'perennial',
    spacingMm: 305,
    spreadMm: 305,
    heightMm: 457,
    sunRequirement: 'fullSun',
    waterRequirement: 'low',
    daysToMaturity: 90,
    plantingWindowStartMonth: 4,
    plantingWindowEndMonth: 7,
    successionIntervalDays: null,
    notes: '',
    isFavorite: false,
    isCustom: false,
    createdAt: '2026-04-12T00:00:00.000Z',
    updatedAt: '2026-04-12T00:00:00.000Z',
  },
];

describe('buildIrrigationRecommendations', () => {
  it('builds zone guidance for growable areas from placed crops', () => {
    expect(
      buildIrrigationRecommendations(plannerDocument, plantDefinitions),
    ).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          zoneId: 'zone-1',
          waterProfile: 'mixed',
          methodLabel: 'Zoned drip',
          summaryLabel: 'Mixed water demand',
          cadenceLabel: 'Split into separate watering runs',
        }),
        expect.objectContaining({
          zoneId: 'zone-2',
          waterProfile: 'high',
          methodLabel: 'Drip ring',
          summaryLabel: 'High water demand',
          cadenceLabel: 'Check moisture daily',
        }),
      ]),
    );
  });

  it('skips non-growable pathway zones', () => {
    const recommendations = buildIrrigationRecommendations(
      plannerDocument,
      plantDefinitions,
    );

    expect(recommendations.find((recommendation) => recommendation.zoneId === 'zone-3')).toBeUndefined();
  });
});
